version: '3.8'

services:
  # --- JENKINS ---
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    user: root # Run as root to access docker socket
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Access to Docker Engine
    networks:
      - devops-net

  # --- SONARQUBE ---
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true # Allow running on simple machines
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
    networks:
      - devops-net

# Create a shared network so they can talk
networks:
  devops-net:

volumes:
  jenkins_home:
  sonar_data:
  sonar_extensions: